################################################################################
# 自动生成的文件。不要编辑！
################################################################################

ELF_SRCS := 
OBJ_SRCS := 
S_SRCS := 
ASM_SRCS := 
C_SRCS := 
S_UPPER_SRCS := 
O_SRCS := 
OBJS := 
SECONDARY_FLASH := 
SECONDARY_SIZE := 
ASM_DEPS := 
S_DEPS := 
S_UPPER_DEPS := 
C_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
applications \
board/CubeMX_Config/Core/Src \
board \
board/port \
libraries/STM32H7xx_HAL/CMSIS/Device/ST/STM32H7xx/Source/Templates/gcc \
libraries/STM32H7xx_HAL/CMSIS/Device/ST/STM32H7xx/Source/Templates \
libraries/STM32H7xx_HAL/STM32H7xx_HAL_Driver/Src \
libraries/drivers \
packages/LVGL-v8.2.0/demos/3d_printer \
packages/LVGL-v8.2.0/demos/benchmark/assets \
packages/LVGL-v8.2.0/demos/benchmark \
packages/LVGL-v8.2.0/demos/keypad_encoder \
packages/LVGL-v8.2.0/demos/music/assets \
packages/LVGL-v8.2.0/demos/music \
packages/LVGL-v8.2.0/demos/stress/assets \
packages/LVGL-v8.2.0/demos/stress \
packages/LVGL-v8.2.0/demos/widgets/assets \
packages/LVGL-v8.2.0/demos/widgets \
packages/LVGL-v8.2.0/env_support/rt-thread \
packages/LVGL-v8.2.0/src/core \
packages/LVGL-v8.2.0/src/draw \
packages/LVGL-v8.2.0/src/draw/nxp_pxp \
packages/LVGL-v8.2.0/src/draw/nxp_vglite \
packages/LVGL-v8.2.0/src/draw/sdl \
packages/LVGL-v8.2.0/src/draw/stm32_dma2d \
packages/LVGL-v8.2.0/src/draw/sw \
packages/LVGL-v8.2.0/src/extra/layouts/flex \
packages/LVGL-v8.2.0/src/extra/layouts/grid \
packages/LVGL-v8.2.0/src/extra/libs/bmp \
packages/LVGL-v8.2.0/src/extra/libs/ffmpeg \
packages/LVGL-v8.2.0/src/extra/libs/freetype \
packages/LVGL-v8.2.0/src/extra/libs/fsdrv \
packages/LVGL-v8.2.0/src/extra/libs/gif \
packages/LVGL-v8.2.0/src/extra/libs/png \
packages/LVGL-v8.2.0/src/extra/libs/qrcode \
packages/LVGL-v8.2.0/src/extra/libs/rlottie \
packages/LVGL-v8.2.0/src/extra/libs/sjpg \
packages/LVGL-v8.2.0/src/extra \
packages/LVGL-v8.2.0/src/extra/others/gridnav \
packages/LVGL-v8.2.0/src/extra/others/monkey \
packages/LVGL-v8.2.0/src/extra/others/snapshot \
packages/LVGL-v8.2.0/src/extra/themes/basic \
packages/LVGL-v8.2.0/src/extra/themes/default \
packages/LVGL-v8.2.0/src/extra/themes/mono \
packages/LVGL-v8.2.0/src/extra/widgets/animimg \
packages/LVGL-v8.2.0/src/extra/widgets/calendar \
packages/LVGL-v8.2.0/src/extra/widgets/chart \
packages/LVGL-v8.2.0/src/extra/widgets/colorwheel \
packages/LVGL-v8.2.0/src/extra/widgets/imgbtn \
packages/LVGL-v8.2.0/src/extra/widgets/keyboard \
packages/LVGL-v8.2.0/src/extra/widgets/led \
packages/LVGL-v8.2.0/src/extra/widgets/list \
packages/LVGL-v8.2.0/src/extra/widgets/menu \
packages/LVGL-v8.2.0/src/extra/widgets/meter \
packages/LVGL-v8.2.0/src/extra/widgets/msgbox \
packages/LVGL-v8.2.0/src/extra/widgets/span \
packages/LVGL-v8.2.0/src/extra/widgets/spinbox \
packages/LVGL-v8.2.0/src/extra/widgets/spinner \
packages/LVGL-v8.2.0/src/extra/widgets/tabview \
packages/LVGL-v8.2.0/src/extra/widgets/tileview \
packages/LVGL-v8.2.0/src/extra/widgets/win \
packages/LVGL-v8.2.0/src/font \
packages/LVGL-v8.2.0/src/hal \
packages/LVGL-v8.2.0/src/misc \
packages/LVGL-v8.2.0/src/widgets \
packages/gt1151-latest/src \
rt-thread/components/dfs/filesystems/devfs \
rt-thread/components/dfs/src \
rt-thread/components/drivers/i2c \
rt-thread/components/drivers/ipc \
rt-thread/components/drivers/misc \
rt-thread/components/drivers/serial \
rt-thread/components/drivers/spi \
rt-thread/components/drivers/touch \
rt-thread/components/finsh \
rt-thread/components/libc/compilers/common \
rt-thread/components/libc/compilers/newlib \
rt-thread/libcpu/arm/common \
rt-thread/libcpu/arm/cortex-m7 \
rt-thread/src \

